# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# trigger:
# - master
variables:
  APOCTL_NAMESPACE: $(NS)
  # APOCTL_CREDS: $(CREDS)

resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main
stages:
- stage: Build
  jobs:
  - job: BuildJob
    displayName: Agent
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
    - task: DownloadSecureFile@1
      name: aporetoCreds
      displayName: 'Aporeto Creds'
      inputs:
        secureFile: 'azure-devops.json'

    - script: |
        echo Installing $(aporetoCreds.secureFilePath) to the trusted .apoctl directory...
        mkdir ~/.apoctl
        mv $(aporetoCreds.secureFilePath) ~/.apoctl/default.creds
        export APOCTL_CREDS=~/.apoctl/default.creds
    - task: CmdLine@2
      inputs:
        script: |
          echo Apoctl variables $APOCTL_CREDS $APOCTL_NAMESPACE
    - task: CmdLine@2
      displayName: Download Apoctl
      inputs:
        script: >
          sudo curl -o /usr/local/bin/apoctl \
            https://download.aporeto.com/apoctl/linux/apoctl && \
          sudo chmod +x /usr/local/bin/apoctl
    - task: CmdLine@2
      displayName: Authenticates the pipeline with Prisma Cloud and list the Namespaces
      inputs:
        script: >-
          apoctl auth verify

          apoctl api list namespace
    - task: CmdLine@2
      displayName: List all namespaces
      inputs:
        script: >-
          apoctl api list namespaces

- stage: Test
  jobs:
  - job: TestOnWindows
    steps:
    - script: echo Testing on Windows!
  - job: TestOnLinux
    steps:
    - script: echo Testing on Linux!
- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: echo Deploying the code!
    
